name: Build and create a release when tag is pushed

on:
    push:
        tags:
          - "v*.*-alpha"
          - "v*.*.*"
          - "v*.*"
    workflow_dispatch:

env:
    APP_NAME: piconesPlus

permissions:
    contents: write

jobs:
    build-release:
        runs-on: ubuntu-latest
        name: Build and create release
        steps:

          - name: Check out this repository with submodules
            uses: actions/checkout@v6
            with:
                submodules: recursive

          - name: Install dependencies
            run: |
                 sudo apt update
                 sudo apt install -y git python3 cmake gcc-arm-none-eabi libnewlib-arm-none-eabi build-essential libusb-1.0-0-dev ninja-build

          - name: Install Pico SDK
            run: |
                 cd $HOME
                 git clone https://github.com/raspberrypi/pico-sdk.git --branch master
                 cd pico-sdk
                 git submodule update --init
                 cd $HOME
                 git clone https://github.com/sekigon-gonnoc/Pico-PIO-USB.git

          - name: Install picotool
            run: |
                 cd $HOME
                 git clone https://github.com/raspberrypi/picotool.git --branch master
                 cd picotool
                 mkdir build
                 cd build
                 cmake .. -DCMAKE_BUILD_TYPE=Release -DPICOTOOL_NO_LIBUSB=ON
                 make -j$(nproc)
                 sudo cp picotool /usr/local/bin/

          - name: Update line containing pico_set_program_version() in CMakelists.txt with tag name.
            run: |
                 input_string=${{ github.ref }}
                 prefix="refs/tags/"
                 tag="No versioninfo found"
                 if [[ $input_string == $prefix* ]]; then
                      echo "The string starts with 'refs/tags/'."
                      tag="${input_string#$prefix}"
                      echo "Tag is ${tag}"
                      sed -i "s/^[[:space:]]*pico_set_program_version(.*/pico_set_program_version(${{ env.APP_NAME }} \"$tag\")/" CMakeLists.txt
                      sed -i "s/VX.X/$tag/" pico_shared/menu.h
                 else
                      echo "The string does not start with 'refs/tags/'."
                 fi
                 grep "pico_set_program_version" CMakeLists.txt
                 grep SWVERSION pico_shared/menu.h

          - name: Build all the .uf2 files
            run: |
                 chmod +x build*.sh bld.sh || exit 1
                 export PICO_SDK_PATH=$HOME/pico-sdk
                 export PICO_PIO_USB_PATH=$HOME/Pico-PIO-USB
                 ./buildAll.sh

          - name: Create release
            uses: softprops/action-gh-release@v3
            if: startsWith(github.ref, 'refs/tags/') && github.event_name == 'push'
            with:
              files: |
                releases/*.uf2
                pico_shared/PCB/pico_nesPCB_v2.6.zip
                pico_shared/PCB/Gerber_PicoNES_Mini_PCB_v2.0.zip
                pico_shared/PCB/Gerber_PicoNES_Micro_v1.2.zip
              body_path: CHANGELOG.md
